trigger:
  branches:
    include:
      - main

resources:
  repositories:
    - repository: cet-iac
      type: git
      name: Cloud Excellence Team/cet-iac
      ref: main

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: build_test
    displayName: Build and test

    jobs:
      - job: unit_test
        steps:
          - template: templates/test/npm-test.yml@cet-iac
            parameters:
              nodeVersion: 18
