trigger: none
pr: none

parameters:
  - name: version
    type: string
    default: patch
    values:
      - patch
      - minor
      - major
      - prepatch
      - preminor
      - premajor
  - name: dryRun
    type: boolean
    default: false

variables:
  - group: team-webb-general-params

resources:
  repositories:
    - repository: cet-iac
      type: git
      name: Cloud Excellence Team/cet-iac
      ref: main

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: build_test
    displayName: Build and test

    jobs:
      - job: unit_test
        steps:
          - template: templates/test/npm-test.yml@cet-iac
            parameters:
              nodeVersion: 18

  - stage: release
    displayName: Release 

    jobs:
      - job: unit_test
        steps:
          - template: templates/npm/push.yml@cet-iac
            parameters:
              nodeVersion: 18
              version: ${{ parameters.version }}
              dryRun: ${{ parameters.dryRun }}
